services:
  db:
    image: mysql:latest
    container_name: db-mysql2
    environment:
      MYSQL_ROOT_PASSWORD: 11121422
      MYSQL_DATABASE: cinema
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      mysql-phpmyadmin:
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db-mysql2
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 11121422
    networks:
      mysql-phpmyadmin:
    restart: always

volumes:
  db_data:
  
networks:
  mysql-phpmyadmin:
